version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "07:23"
      timezone: Etc/UTC
    open-pull-requests-limit: 2
    groups:
      automerge-actions-patches:
        patterns: ["*"]
        update-types: [patch]
      review-actions-minors:
        patterns: ["*"]
        update-types: [minor]
    cooldown:
      default-days: 7

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "07:23"
      timezone: Etc/UTC
    open-pull-requests-limit: 2
    allow:
      - dependency-type: direct
    groups:
      automerge-go-patches:
        patterns: ["*"]
        update-types: [patch]
      review-go-minors:
        patterns: ["*"]
        update-types: [minor]
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "07:23"
      timezone: Etc/UTC
    open-pull-requests-limit: 2
    allow:
      - dependency-type: direct
    groups:
      automerge-frontend-patches:
        patterns: ["*"]
        update-types: [patch]
      review-frontend-minors:
        patterns: ["*"]
        update-types: [minor]
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /contrib/workload-identity/image
    schedule:
      interval: monthly
      day: monday
      time: "07:23"
      timezone: Etc/UTC
    open-pull-requests-limit: 2
    groups:
      review-image-updates:
        patterns: ["*"]
        update-types: [minor, patch]
    cooldown:
      default-days: 7
